# Generated file - do not commit this file.
{
  "name": "queen_validators",
  "version": "1.0.0",
  "homepage": "https://github.com/FlutterQueen/validators",
  "environment": {
    "sdk": ">=2.17.0 <3.0.0",
    "flutter": ">=1.17.0"
  },
  "description": "collection of validation methods and rules for flutter form with ZERO extra widgets",
  "dependencies": {
    "email_validator": "^2.0.1",
    "flutter": {
      "sdk": "flutter"
    }
  },
  "dev_dependencies": {
    "flutter_test": {
      "sdk": "flutter"
    },
    "lint": "^1.8.2"
  },
  "repository": "https://github.com/FlutterQueen/validators",
  "issue_tracker": "https://github.com/FlutterQueen/validators/issues"
}