# Generated file - do not commit this file.
{
  "name": "qcore",
  "version": "1.0.0",
  "environment": {
    "sdk": ">=2.18.0 <3.0.0"
  },
  "description": "A starting point for Dart libraries or applications.",
  "dev_dependencies": {
    "lints": "^2.0.0",
    "test": "^1.16.0"
  }
}