# Generated file - do not commit this file.
{
  "name": "queen_example",
  "version": "1.0.0+1",
  "publish_to": "none",
  "environment": {
    "sdk": ">=2.15.1 <3.0.0"
  },
  "description": "A new Flutter project.",
  "dependencies": {
    "flutter": {
      "sdk": "flutter"
    },
    "cupertino_icons": "^1.0.2",
    "queen": {
      "path": "H:\\\\queen\\\\packages\\\\queen"
    }
  },
  "dev_dependencies": {
    "flutter_test": {
      "sdk": "flutter"
    }
  },
  "dependency_overrides": {
    "flutter_readable": {
      "path": "..\\\\..\\\\flutter_readable"
    },
    "locators": {
      "path": "..\\\\..\\\\locators"
    },
    "nations": {
      "path": "..\\\\..\\\\nations"
    },
    "qcore": {
      "path": "..\\\\..\\\\qcore"
    },
    "qprefs": {
      "path": "..\\\\..\\\\qprefs"
    },
    "queen": {
      "path": ".."
    },
    "queen_validators": {
      "path": "..\\\\..\\\\validators"
    },
    "readable": {
      "path": "..\\\\..\\\\readable"
    }
  },
  "lint": "^1.10.0",
  "flutter": {
    "uses-material-design": true
  }
}