# Generated file - do not commit this file.
{
  "name": "nations",
  "version": "0.0.7",
  "homepage": "https://github.com/FlutterQueen/nations",
  "environment": {
    "sdk": ">=2.17.0 <3.0.0",
    "flutter": ">=1.17.0"
  },
  "description": "queen support for localization in flutter, part of queen",
  "dependencies": {
    "flutter": {
      "sdk": "flutter"
    },
    "flutter_readable": "^0.0.2",
    "locators": "0.0.1",
    "nations_assets": "^0.0.1",
    "qcore": "0.0.1",
    "qprefs": "0.0.1"
  },
  "dev_dependencies": {
    "flutter_test": {
      "sdk": "flutter"
    },
    "lint": "^1.7.2"
  },
  "dependency_overrides": {
    "platform": "3.1.0",
    "flutter_readable": {
      "path": "..\\\\flutter_readable"
    },
    "locators": {
      "path": "..\\\\locators"
    },
    "qcore": {
      "path": "..\\\\qcore"
    },
    "qprefs": {
      "path": "..\\\\qprefs"
    },
    "readable": {
      "path": "..\\\\readable"
    }
  },
  "issue_tracker": "https://github.com/FlutterQueen/nations/issues"
}