# Generated file - do not commit this file.
{
  "name": "locators",
  "version": "1.0.0",
  "environment": {
    "sdk": ">=2.18.0 <3.0.0"
  },
  "description": "A sample command-line application.",
  "dependencies": {
    "meta": "^1.8.0"
  },
  "dev_dependencies": {
    "lints": "^2.0.0",
    "test": "^1.16.0"
  }
}