name: queen_example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  queen:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

lint: ^1.10.0
flutter:
  uses-material-design: true
