# Generated file - do not commit this file.
{
  "name": "readable",
  "version": "0.0.5",
  "homepage": "https://github.com/FlutterQueen/readable",
  "environment": {
    "sdk": ">=2.12.0 <3.0.0"
  },
  "description": "extensions and helpers for dart to save time , make the code more readable and smaller",
  "dev_dependencies": {
    "lint": "^1.7.2",
    "test": "^1.20.0"
  }
}