#The name of your workflow.
name: check
# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: [master, dev]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Activate melos latest
        run: flutter pub global activate melos

      - name: bootstrap
        run: melos bs

      - name: "Analyze"
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
          fatal-warnings: true
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v1.5.3

      - name: Activate melos latest and bootstrap
        run: flutter pub global activate melos && melos bs

      - name: check lint
        run: melos run test_coverage
# until we fix ths issues
# https://github.com/FlutterQueen/queen/issues/5
# - name: Check Code Coverage
# uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
